"""Detector settings for layer 08 subjective framing and authority validation."""

SUBJECTIVITY_CLASSIFIER_URL_ENV = "SUBJECTIVITY_CLASSIFIER_URL"
SUBJECTIVITY_CLASSIFIER_MODULE = "subjectivity.classify"

OBJECTIVE_MARKERS = (
    "studies show",
    "research shows",
    "evidence shows",
    "it is proven",
    "the fact is",
    "objectively",
    "data shows",
    "experts agree",
    "according to",
    "must be understood",
    "i am a",
    "i'm a",
    "i live",
    "i work",
    "my wife",
    "my husband",
    "my partner",
    "my children",
    "my kids",
    "i voted",
    "i cast my vote",
    "i completed",
    "i earned",
    "i oversee",
    "i manage",
)

SUBJECTIVE_MARKERS = (
    "i think",
    "i feel",
    "i believe",
    "to me",
    "for me",
    "from my perspective",
    "in my experience",
    "i tend",
    "i would",
    "it seems",
    "i suppose",
    "i value",
    "i care",
    "i worry",
    "i prefer",
    "i appreciate",
    "i support",
    "i'm wary",
    "i am wary",
    "i felt",
    "i find",
    "i see",
    "for me",
    "personally",
    "my view",
    "my perspective",
    "my experience",
    "what matters to me",
)

FIRST_PERSON_MARKERS = (
    "i ",
    "i'm",
    "i’ve",
    "i've",
    "i’d",
    "i'd",
    "i’ll",
    "i'll",
    "my ",
    "me ",
    "mine",
)

OBJECTIVE_STRUCTURE_MARKERS = (
    "i am",
    "i'm",
    "i live",
    "i work",
    "i have",
    "i completed",
    "i earned",
    "i oversee",
    "i manage",
    "there is",
    "there are",
    "because",
    "which",
    "where",
)

LIMITED_EXPERTISE_MARKERS = (
    "i'm not an expert",
    "i am not an expert",
    "i'm no expert",
    "i am no expert",
    "not my area of expertise",
    "i don't know much about",
    "i do not know much about",
    "i only know the broad outline",
    "i don't know the topic in depth",
    "i do not know the topic in depth",
)

LOW_STAKES_ADVICE_MARKERS = (
    "what should i give",
    "what should i get",
    "gift",
    "present",
    "mother's day",
    "mothers day",
    "birthday",
    "anniversary",
    "dinner",
    "cook",
    "recipe",
    "movie",
    "book",
    "holiday",
    "weekend",
    "recommend",
    "suggest",
    "advice",
)

HIGH_STAKES_ADVICE_MARKERS = (
    "medical",
    "diagnose",
    "treatment",
    "legal",
    "tax",
    "investment",
    "financial",
    "therapy",
    "mental health",
)
